import type {Finding,Trace} from "./types";
const f=(ruleId:string,severity:Finding["severity"],faultLayer:Finding["faultLayer"],conclusion:string,evidence:string[],needsMoreEvidence=false):Finding=>({ruleId,severity,faultLayer,conclusion,evidence,needsMoreEvidence});
export function runRules(t:Trace):Finding[]{const out:Finding[]=[];const logs=(t.logs??[]).join("\n");const sse=t.sse??[];
if(t.statusCode===429) out.push(f("http-429","medium","provider",`观察到 HTTP 429；${t.retryCount===undefined?"未见 retry_count，需补充重试证据":`retry_count=${t.retryCount}${t.retryReason?`，原因：${t.retryReason}`:""}`}`, ["status_code=429"],t.retryCount===undefined));
if((t.statusCode??0)>=500) out.push(f("http-5xx","high",t.upstreamResponse?"upstream":"unknown",t.upstreamResponse?"已观察到上游响应异常。":"观察到 5xx，但缺少上游响应，无法区分中转与上游。",[`status_code=${t.statusCode}`],!t.upstreamResponse));
if(/context canceled|client_gone|timeout|超时/i.test(logs))out.push(f("cancellation","high","gateway","日志含取消、客户端离开或超时线索，可能发生提前断流。",[logs.match(/.{0,30}(context canceled|client_gone|timeout|超时).{0,40}/i)?.[0]??"日志线索"],false));
const starts=new Set(sse.filter(x=>/content_block_start/.test(x)).map(x=>x.match(/index["=: ]+(\d+)/)?.[1]??"?"));const stops=sse.filter(x=>/content_block_stop/.test(x)); if(stops.some(x=>!starts.has(x.match(/index["=: ]+(\d+)/)?.[1]??"?")))out.push(f("anthropic-sse-lifecycle","high","adapter","SSE 中 content_block_stop 缺少对应 start。",stops,false));
const idx=sse.map(x=>Number(x.match(/index["=: ]+(\d+)/)?.[1])).filter(Number.isFinite);if(idx.some((n,i)=>i>0&&n>idx[i-1]+1))out.push(f("anthropic-sse-index","medium","adapter","SSE content index 出现跳变。",sse,false));if(t.statusCode===200&&sse.some(x=>/event:\s*error|"error"/.test(x)))out.push(f("sse-after-200","high","upstream","HTTP 200 后仍出现 SSE error 事件。",sse.filter(x=>/error/.test(x)),false));
const a=t.clientRequest??{},b=t.transformedRequest??{};const keys=["model","system","messages","tools","thinking","temperature","max_tokens","headers","cache_control"];const diffs=keys.filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])&& (a[k]!==undefined||b[k]!==undefined));if(diffs.length)out.push(f("protocol-diff","medium","adapter",`客户端请求与转换后请求字段差异：${diffs.join("、")}。`,diffs,false));
if((t.route??"").toLowerCase().includes("bedrock")&&JSON.stringify(a).includes("web_search_20250305")&&JSON.stringify(t.upstreamResponse??{}).includes("ValidationException"))out.push(f("bedrock-tool-compatibility","high","adapter","Bedrock 路由携带 web_search_20250305，且上游返回 ValidationException，工具能力不兼容。",["route=bedrock","web_search_20250305","ValidationException"],false));
const events=JSON.stringify(a);if(events.includes("tool_result")&&!events.includes("tool_use"))out.push(f("tool-lifecycle","high","client","存在 tool_result 但缺少 tool_use。",["tool_result"],false));
if(!JSON.stringify(a).includes("cache")&&!JSON.stringify(t.upstreamResponse??{}).includes("cache"))out.push(f("cache-evidence","low","unknown","缓存证据不足，无法确认 cache miss。",["未找到可比较请求、缓存字段或 usage"],true));return out}
